
language: php

sudo: true

dist: trusty

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1


services:
  - memcached
  - mysql

before_script:
    - if [ ${TRAVIS_PHP_VERSION:0:3} != "5.2" ]; then travis_retry composer --prefer-source --dev install; fi
    - if [ ${TRAVIS_PHP_VERSION:0:3} <= "5.6" ]; then  phpenv config-add travis.ini; fi
    - if [ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]; then  composer global require phpunit/phpunit 6.4.1; fi
    - mysql -e "create database IF NOT EXISTS test;" -uroot

install:
     - git clone --depth=50 --branch=master git://github.com/smarty-php/smarty-phpunit.git

script:
   - cd smarty-phpunit
<<<<<<< HEAD
   - if [[ $TRAVIS_PHP_VERSION = 7.* || $TRAVIS_PHP_VERSION = nightly ]]; then
        ./vendor/bin/phpunit
    else
        phpunit ./
=======
   - if [[ $TRAVIS_PHP_VERSION = 7.1 || $TRAVIS_PHP_VERSION = nightly ]]; then
        $COMPOSER_BIN_DIR/phpunit ./;
    else
        phpunit ./;
>>>>>>> parent of e9e97cc... Use phpunit 6.4.1 for PHP 7.1
    fi

