language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

services:
  - memcached
  - mysql
  
before_script:
    - travis_retry composer --prefer-source --dev install
    - mysql -e "create database IF NOT EXISTS test;" -uroot

install:
   - git clone --depth=50 --branch=master git://github.com/smarty-php/smarty-phpunit.git

script:
   - cd smarty-phpunit
   - phpunit ./

