language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
  - hhvm-nightly

allow_failures:
    - php: nightly
    - php: hhvm-nightly

install:
   - composer require smarty/smarty-php:3.1.*@dev

script: phpunit --configuration ../smarty-php/phpunit.xml