language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
  - hhvm-nightly

allow_failures:
    - php: nightly
    - php: hhvm-nightly

install:
   - git://github.com/smarty-php/smarty-phpunit.git


script: phpunit --configuration ./../smarty-phpunit/phpunit.xml